# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2656621abea7beebffb356ef6b4aef2ba75e0b5a1aa842e39dd7983725269531d3123a6137021376da1b59a708249f958192822d6cebfa534aefea76ff856855

test:
  secret_key_base: ebd335092620e4b94054c0ced2ac11bfb204eecb287308c3f575cde098aa7bd3b997fcc1269dbc969eb543f41465a1cd825f344a674b9a9fb0536b8d7d2cf039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
